# Generated by Django 4.1.5 on 2023-04-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_address_shipping_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='company',
        ),
        migrations.AlterField(
            model_name='address',
            name='order_note',
            field=models.TextField(default=None, max_length=1500, null=True),
        ),
    ]
