# Generated by Django 4.1.7 on 2023-04-05 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_address_country_address_state_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='billing_address',
            new_name='shipping_address',
        ),
    ]
