# Generated by Django 4.1.5 on 2023-04-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_cartitem_variations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('discount', models.DecimalField(decimal_places=0, max_digits=2)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
