# Generated by Django 4.1.5 on 2023-04-01 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
