# Generated by Django 4.1.5 on 2023-04-04 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_country_order_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderNumber',
            new_name='order_number',
        ),
    ]
